services:
  - type: web
    name: inventory-pro
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

    autoDeploy: true
    rootDir: ./
    region: oregon